import type { ConnectorDef } from '../types';

export const CONNECTORS: Record<string, ConnectorDef> = {
  'neutrik-d': {
    name: 'Neutrik D-Type',
    desc: 'XLR/BNC/HDMI/EtherCon/USB — universal',
    cut: 'd-shape',
    w: 24, h: 28, r: 11.9,
    color: '#4a90d9', icon: '◉',
    depthBehind: 30,
    mountHoles: 2,
  },
  'bnc': {
    name: 'BNC Bulkhead',
    desc: 'SDI 75Ω / RF 50Ω (⌀9.5mm)',
    cut: 'round',
    w: 14, h: 14, r: 4.75,
    color: '#d4a017', icon: '◎',
    depthBehind: 22,
  },
  'rj45-ks': {
    name: 'RJ45 Keystone',
    desc: 'Cat5e/6/6a (14.9×19.2mm)',
    cut: 'rect',
    w: 16.5, h: 19.2,
    color: '#2d7a2e', icon: '▣',
    depthBehind: 28,
  },
  'sma': {
    name: 'SMA Bulkhead',
    desc: 'RF ⌀6.35mm (to 18 GHz)',
    cut: 'round',
    w: 10, h: 10, r: 3.175,
    color: '#c41e3a', icon: '●',
    depthBehind: 15,
  },
  'fiber-lc': {
    name: 'LC Duplex Fiber',
    desc: 'SM/MM adapter (26×18mm)',
    cut: 'rect',
    w: 26, h: 18,
    color: '#0056b3', icon: '⊞',
    depthBehind: 32,
    mountHoles: 2,
  },
  'fiber-sc': {
    name: 'SC Simplex Fiber',
    desc: 'SM/MM adapter (16×20mm)',
    cut: 'rect',
    w: 16, h: 20,
    color: '#6a5acd', icon: '⊡',
    depthBehind: 35,
    mountHoles: 2,
  },
  'usb-a': {
    name: 'USB-A Panel',
    desc: 'USB 2.0/3.0 (13.1×5.6mm)',
    cut: 'rect',
    w: 16, h: 8,
    color: '#555555', icon: '▯',
    depthBehind: 25,
  },
  'hdmi': {
    name: 'HDMI Feedthrough',
    desc: 'HDMI panel mount (21×9.5mm)',
    cut: 'rect',
    w: 24, h: 12,
    color: '#1a1a2e', icon: '▬',
    depthBehind: 30,
  },
  'db9': {
    name: 'DB-9 / DE-9',
    desc: 'Serial RS-232 (17.5×9.4mm)',
    cut: 'd-sub',
    w: 20, h: 12,
    color: '#7c3aed', icon: '⊏',
    depthBehind: 28,
    mountHoles: 2,
  },
  'powercon': {
    name: 'PowerCON',
    desc: 'Neutrik AC power (D-type cutout)',
    cut: 'd-shape',
    w: 24, h: 28, r: 11.9,
    color: '#dc2626', icon: '⚡',
    depthBehind: 35,
    mountHoles: 2,
  },
};
